# Generated by Django 4.2.6 on 2023-11-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v2captcha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
